config/routes.rb
Rails.application.routes.draw do
  get 'audiobooks/listen'
  resources :audiobooks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audiobook.rb
require 'nokogiri'
require 'open-uri'

class Audiobook < ApplicationRecord

  def doc_parse
    doc = Nokogiri::HTML(open("https://www.gutenberg.org/browse/categories/1"))
    nodes = doc.css('a:contains("Embankment at Night")')
    nodes.each do |m|
      html = "https://www.gutenberg.org"
      if !m["href"].include?('author')
       slug = m["href"]
       html += slug
      end
    doc1 = Nokogiri::HTML(open(html))
    audio = doc1.css('td[content*="mpeg"] a[href]')
    str = ""
    audio.each do |node|
      str += "<br> #{node.to_s}"
    end
    return str
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/audiobooks_controller.rb
class AudiobooksController < ApplicationController
  def listen
    @message = "We are going to listen to free audio!" 
  end

  def new
  end

  def index
  end

  def create
    @book = Audiobook.new(book_params)
    @book.save
    #pass the instance to the path, and it will know the id of that instance
    redirect_to audiobook_path(@book)
  end

  def show
    @book = Audiobook.find(params[:id])
    @audio = @book.doc_parse
  end

  private
  def book_params
    params.require(:book).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audiobooks_helper.rb
module AudiobooksHelper
end

app/views/audiobooks/new.html.erb
<h1>Audiobooks</h1>
<%= @message %>
<%= form_with scope: :book, url: audiobooks_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/audiobooks/show.html.erb
<h1>Your book is added</h1>
<p>
  <%= @book.title %>
  <%= @audio.html_safe %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audioapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>